version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: daryapopk/kittygram_backend_1
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    depends_on:
      - db
  frontend:
    image: daryapopk/kittygram_frontend_1
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: daryapopk/kittygram_gateway_1
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/app/media/
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend

